default:
  image: 'cimg/python:3.11'

stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - pip install hatch
    - hatch build
    - shasum -a 256 dist/* > dist/checksums.txt
  artifacts:
      paths:
        - dist/
  only:
    - /^v[0-9]+\.[0-9]+\.[0-9]+.*/
  except:
    - branches

deploy-job:
  stage: deploy
  script:
    - pip install hatch keyrings.alt
    - export HATCH_INDEX_USER=__token__
    - export HATCH_INDEX_AUTH=$PYPI_PASSWORD
    - hatch publish
  needs:
    - build-job
  only:
    - /^v[0-9]+\.[0-9]+\.[0-9]+.*/
  except:
    - branches
